AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  goal2:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: hello.handler
      Architectures: [arm64]
      Runtime: provided.al2
      MemorySize: 128
      Timeout: 3
    Metadata:
      BuildMethod: makefile
